config/routes.rb
Rails.application.routes.draw do
  #devise_for :admin_users

  devise_for :admin_users, controllers: {
    sessions: 'admin_users/sessions', registrations:'admin_users/registrations'
  }

  devise_scope :admin_user do  
    get '/admin_users/sign_out' => 'devise/sessions#destroy'     
 end 
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'welcome#index'
  get '/dashboard', to: 'admin#dashboard', as: 'dashboard'
  namespace :admin do
      get 'dashboard', to: 'dashboard#index'
      resources :students
      resources :courses
      resources :projects
    end    
  end

app/views/shared/_admin_sidebar.html.erb
    <div class="sidebar">
            <div class="profile">
                    <img src="https://w1.pngwing.com/pngs/743/500/png-transparent-circle-silhouette-logo-user-user-profile-green-facial-expression-nose-cartoon.png" alt="profile_picture">
                    <h3>Admin</h3>
                    <p>welcome!</p>
                </div>
            <ul>
                <li>
                    <a href="<%= dashboard_path %>">
                    <i class="fas fa-home menu-icon"></i>
                    <span class="menu-item">Dashboard</span>
                    </a>
                </li>
                <li>
                    <a href="<%= admin_students_path %>">
                    <i class="fas fa-users menu-icon"></i>
                    <span class="menu-item">Students</span>
                    </a>
                </li>
                <li>
                <% if admin_user_signed_in? %>
                    <%=link_to "Sign Out", destroy_admin_user_session_path, 'data-turbo-method': :delete, class:"nav-link" %>
                <% end %>
                </li>
            </ul>
        </div>
    </div>

app/views/shared/_footer.html.erb
<footer class="bg-dark text-center text-white">
  <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
    © 2023 Copyright:
    <a class="text-white" href="/">MyApp.com</a>
  </div>
</footer>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark ">
      <div class="container-fluid ">
        <a class="navbar-brand" href="/">
        <img src="https://upload.wikimedia.org/wikipedia/en/thumb/b/bb/Carnegie_Mellon_University_seal.svg/1200px-Carnegie_Mellon_University_seal.svg.png" width="35" height="28" style="margin-right: 10px";>My App</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="<%= admin_students_path %>">Students</a>
            </li>
            <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="<%= admin_courses_path %>">Courses</a>
            </li>
            <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="<%= admin_projects_path %>">Projects</a>
            </li>
          </ul>
          
        </div>
      </div>
    </nav>