config/routes.rb
Rails.application.routes.draw do
  #devise_for :admin_users

  devise_for :admin_users, controllers: {
    sessions: 'admin_users/sessions', registrations:'admin_users/registrations'
  }

  devise_scope :admin_user do  
    get '/admin_users/sign_out' => 'devise/sessions#destroy'     
 end 
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'welcome#index'
  get '/dashboard', to: 'admin#dashboard', as: 'dashboard'
  namespace :admin do
      get 'dashboard', to: 'dashboard#index'
      resources :students
      resources :courses
      resources :projects
    end    
  end

app/models/project.rb
class Project < ApplicationRecord
    has_many :student_projects
    has_many :students, through: :student_projects
end

app/controllers/admin/projects_controller.rb
class Admin::ProjectsController < ApplicationController
    layout 'application'
    
        def index
          @projects = Project.all
        end
      
        def new
          @project = Project.new
        end
      
        def create
          @project = Project.new(project_params)
          if @project.save
            redirect_to admin_projects_path , notice: 'Project has successfully created'
          else
            render :new
          end
        end
      
        def show
            @project = Project.find(params[:id])
        end
           
        def edit
            @project = Project.find(params[:id])
        end

        def update
          @project = Project.find(params[:id])
          if @project.update(project_params)
            redirect_to admin_project_path(@project), notice: 'Project has successfully updated'
          else
            render :edit
          end
        end 
      
        def destroy
          @project = Project.find(params[:id])
          @project.destroy
          redirect_to admin_projects_path, notice: 'Project has successfully deleted.'
        end
        
      
        private
      
        def project_params
          params.require(:project).permit(:name, :status)
        end
  end

app/controllers/projects_controller.rb
class ProjectsController < ActionController::Base
    layout 'application'
    
        def index
          @projects = Project.all
        end
      
        def new
          @project = Project.new
        end
      
        def create
          @project = Project.new(project_params)
          if @project.save
            redirect_to projects_path , notice: 'Project has successfully created'
          else
            render :new
          end
        end
      
        def show
          @project = Project.find(params[:id])
        end
      
        def edit
          @project = Project.find(params[:id])
        end
      
        def update
          @project = Project.find(params[:id])
          if @project.update(project_params)
            redirect_to project_path(@project), notice: 'Project has successfully updated'
          else
            render :edit
          end
        end 
      
        def destroy
          @project = Project.find(params[:id])
          @project.destroy
          redirect_to project_path, notice: 'Project has successfully deleted.'
        end
        
      
        private
      
        def course_params
          params.require(:project).permit(:name, :status)
        end
  end
  

app/views/admin/projects/_form.html.erb
<%= form_with(model:[:admin,@project]) do |form| %>
    <div style='color:red;'>
    <% @project.errors.full_messages.each do |message| %>
        <div><%= message %></div>
        <% end %>
    </div>
    
    <div class="form-group">
        <%= form.label :name %>
        <%= form.text_field :name , class:"form-control"%>
    </div>

    <div class="form-group">
        <%= form.label :status %>
        <%= form.text_field :status ,class:"form-control"%>
    </div>

    <div class="form-group mt-2" >
        <%= form.submit  class:"btn btn-primary"%>
    </div>
<% end %>

app/views/admin/projects/edit.html.erb
<div class="col-lg-12">
<div class="card rounded-3 shadow mt-3 mb-3">
<h1>Edit Project</h1>
<%= render "form", project: @project %>
</br>
<div >
<%= link_to 'Back', admin_projects_path, class: "btn btn-outline-primary btn-sm" %>
</div>
</div>
</div>

app/views/admin/projects/index.html.erb
<h1>Listing Projects</h1>
<%= link_to'Add Project',new_admin_project_path %>
<table class="table table-striped">
  <thead>
    <tr class="table-dark text-center">
        <div class="col">
          <th>Name</th>
        </div>
        <div class="col">
          <th colspan="3">Actions</th>
        </div>
    </tr>
  </thead>
  <tbody>
    <% @projects.each do |project| %>
        <tr>
        <td><%= project.name %></td>
        <td><%= link_to 'View', admin_project_path(project) %></td> 
        <td><%= link_to 'Edit', edit_admin_project_path(project) %></td> 
        <td><%= link_to 'Delete', admin_project_path(project), data: { turbo_method: :delete, confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/projects/new.html.erb
<div class="col-lg-12">
<div class="card rounded-3 shadow mt-3 mb-3">
<h1>Add Project</h1>
<%= render "form", project: @project %>
</br>
<div >
<%= link_to 'Back', admin_projects_path, class: "btn btn-outline-primary btn-sm" %>
</div>
</div>
</div>

app/views/admin/projects/show.html.erb
<div class="col-lg-12">
<div class="card rounded-3 shadow mt-3 mb-5">
    <h1>Project Detail</h1>

    <p><strong>Name:</strong><%= @project.name%></p>
    <p><strong> Status:</strong><%= @project.status %></p>
    <div class="row mb-5 mt-3">
    <div class="col-md-4">
    <%= link_to 'Back', admin_projects_path, class: "btn btn-outline-primary btn-sm" %>
    </div>
    <div class="col-md-4">
    <%= link_to 'edit', edit_admin_project_path(@project), class: "btn btn-outline-secondary btn-sm" %>
    </div>
    <div class="col-md-4">
    <%= link_to 'Delete', admin_project_path(@project), class: "btn btn-outline-danger btn-sm", data: {
  turbo_method: :delete,
  turbo_confirm: "Are you sure?"
} %>
    </div>
    </div>
</div>
</div>